<a href="https://colab.research.google.com/github/gijopeter/Advanced_TensorFlow/blob/main/Generative%20Deep%20Learning%20with%20TensorFlow/Week1/einsum_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([1,2,3,4],shape=(2,2))

In [3]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
tf.linalg.einsum('ij,ij->ij', x ,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [6]:
tf.square(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [10]:
xT = tf.transpose(x)
xT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [16]:
tf.linalg.einsum('ij,jk->ik', xT ,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

In [14]:
tf.matmul( xT ,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

In [15]:
tf.linalg.einsum('ik,jk->', xT ,x)

<tf.Tensor: shape=(), dtype=int32, numpy=54>